version: '3'

services:
  web:
    build: ./nginx/
    image: nginx
    container_name: nginx
    hostname: nginx
    tty: true
    ports:
      - "8080:80"
    networks:
      - webapp
    depends_on:
      - app

  app:
    build: ./node/
    image:  node
    container_name: nodeapp
    hostname: nodeapp
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    tty: true
    ports:
      - "3000:3000"
    networks:
      - webapp
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: db
    hostname: db
    restart: always
    tty: true
    command:
    - --innodb-use-native-aio=0
    - --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./init/createtable.sql:/docker-entrypoint-initdb.d/createtable.sql:ro
      - ./data_mysql:/var/lib/mysql:rw
    ports:
      - "3306:3306"
    networks:
      - webapp

networks:
  webapp:
    driver: bridge